unreadable_zip: "Нечитаемый zip архив."
s3_error: "Невозможно скачать файл из s3."
no_task: "Нет файла задачи внутри архива."
extension: "Неправильное расширение файла задачи внутри архива."
unreadable_file: "Невозможно прочитать файл."
no_data_field: "Нет поля дата в файле задачи."
no_split: "Нет поля test в файле задачи."
no_outputs_field_for_doc: "Невозможно получить поле outputs из файла задачи для документа с порядковым номером (не id) example_number."
no_meta_field_for_doc: "Невозможно получить поле meta из файла задачи для документа с порядковым номером (не id) example_number."
no_id_field_for_doc: "Невозможно получить поле id из файла задачи для документа с порядковым номером (не id) example_number."
no_id: "Нет документа с id в файле задачи."
doc_output_type_error: "Тип поля outputs не соответствует ожидаемому типу."
doc_parse_output_error: "Ошибка получения outputs для документа (поле есть, но распарсить его не получается)."
task_system_error: "Непредвиденная системная ошибка при валидации и оценке задачи."